services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $syliusResources: '%sylius.resources%'

    app_fixture:
        namespace: App\
        resource: '../../src/Monofony/Pack/ApiPack/.recipe/src/*'
        exclude: '../../src/Monofony/Pack/ApiPack/.recipe/src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
