framework:
    #esi:             ~
    translator:
        fallbacks: ["%locale%"]
        paths:
            - '%kernel.project_dir%/src/Monofony/Pack/CorePack/Recipe/translations'
    secret:          '%env(APP_SECRET)%'
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:
        enabled: true
        mapping:
            paths: ['%kernel.project_dir%/src/Monofony/Pack/ApiPack/Recipe/config/serialization/']
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    php_errors:
        log: true

