imports:
    - { resource: '../../src/Monofony/Bundle/CoreBundle/Recipe/config/packages/monofony_core.yaml' }
    - { resource: '../../src/Monofony/Pack/AdminPack/Recipe/config/sylius/grids/**/*.yaml' }
