imports:
    - { resource: '../../src/Monofony/Pack/CorePack/.recipe/config/packages/monofony_core.yaml' }
    - { resource: '../../src/Monofony/Pack/AdminPack/.recipe/config/sylius/grids/**/*.yaml' }
