imports:
    - ../src/Monofony/Bundle/CoreBundle/Recipe/config/suites/cli/installer.yaml

    - ../src/Monofony/Pack/AdminPack/Recipe/config/suites/ui/admin/dashboard.yaml
    - ../src/Monofony/Pack/AdminPack/Recipe/config/suites/ui/customer/managing_customers.yaml
    - ../src/Monofony/Pack/AdminPack/Recipe/config/suites/ui/user/managing_administrators.yaml

    - ../src/Monofony/Pack/FrontPack/Recipe/config/suites/ui/account/customer.yaml
    - ../src/Monofony/Pack/FrontPack/Recipe/config/suites/ui/account/login.yaml
    - ../src/Monofony/Pack/FrontPack/Recipe/config/suites/ui/account/registration.yaml
